<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
    <div class="jumbotron">
        <h1>Sobre</h1>       
    </div>
    <div class="col-md-12">
        <h2>A instituição</h2>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
            Possimus consequatur voluptatum culpa suscipit incidunt maxime
            ad fuga unde deserunt! Incidunt possimus, officiis libero minima
            dolorum laboriosam unde laudantium ut veritatis?
        </p>  
        <h2>Nossas metas</h2>  
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
            Possimus consequatur voluptatum culpa suscipit incidunt maxime
            ad fuga unde deserunt! Incidunt possimus, officiis libero minima
            dolorum laboriosam unde laudantium ut veritatis?
        </p>    
        <h2>Valores</h2>  
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. 
            Possimus consequatur voluptatum culpa suscipit incidunt maxime
            ad fuga unde deserunt! Incidunt possimus, officiis libero minima
            dolorum laboriosam unde laudantium ut veritatis?
        </p>    
    </div>
</div> 
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
    
