<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">

    <div class="jumbotron">
        <h1>Entre em contato conosco</h1> 
    </div>
    <div class="col-md-12">
        <h2>Fale conosco pelos meios de contato abaixo:</h2>
        <p>
            Telefone: <a href="tel:+5551981189706"><strong>(51)981189706</strong></a><br>
            Email: <a href="mailto:dosantosbjj@gmail.com"><strong>dosantosbjj@gmail.com</strong></a>
        </p>
        <p>
            Ou através do formulário abaixo:
            <form action="">  
            <div class="form-group">
                    <label for="name">Nome:</label>
                    <input type="text" name="nome" class="form-control" placeholder="Nome completo..." required>
                </div>              
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email" class="form-control" placeholder="Email para contato..." required>
                </div>
                <div class="form-group">
                    <label for="assunto">Assunto</label>
                    <input type="text" name="assunto" class="form-control" placeholder="Assunto..." required>
                </div>
                <div class="form-group">
                    <label for="mensagem">Mensagem</label>
                    <textarea name="mensagem" class="form-control" cols="10" rows="20" placeholder="Digite sua mensagem..." required>

                    </textarea>
                </div>
                <button type="submit" class="btn btn-default">Enviar contato</button>
            </form>
        </p>
    </div>
</div> 
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
    
