<?php require VIEWS_PATH . 'includes/header.phtml';?>
<div class="container">
    <div class="jumbotron">
        <h1>Bem vindo ao projeto 1</h1>
        <p>
            Projeto criado na maratona de PHP OO no cursinho da code experts.
        <p>
            <a class="btn btn-lg btn-primary" href="http://bit.ly/ce-learn" role="button">Saiba mais... &raquo;</a>
        </p>
    </div>
</div> 
<?php require VIEWS_PATH . 'includes/footer.phtml';?>
    
